# Cleanup packages once Nginx is installed
# https://blog.engineyard.com/2011/useful-rewrites-for-nginx
---

- block:
    - name: Cleanup Nginx packages
      ansible.builtin.package:
        name: '{{ nginx_cleanup_packages }}'
        state: absent

    - name: Cleanup Nginx Python packages
      ansible.builtin.pip:
        name: cryptography
        executable: '{{ nginx_pip_path }}'
        state: absent
      environment: '{{ nginx_pip_environment }}'

    - name: Cleanup source directory
      ansible.builtin.file:
        path: '{{ local_source_directory }}'
        state: absent
  become: '{{ do_become }}'
  tags: packages
