# Install and configure Nginx, daemonize with Supervisor, enable our Site
# https://blog.engineyard.com/2011/useful-rewrites-for-nginx
---

- block:
    - import_tasks: facts.yml
    - import_tasks: '{{ nginx_role_action }}.yml'
  tags: nginx
