---

- name: Install Nginx build dependencies
  ansible.builtin.apt:
    name: nginx
    state: build-dep
  become: '{{ do_become }}'
  tags: [nginx, packages] # FIXME Remove when this is fixed https://github.com/ansible/ansible/issues/30882
