---

- name: Install Nginx build dependencies
  ansible.builtin.command:
    echo "dnf builddep --assume{{ 'no' if ansible_check_mode else 'yes' }} nginx"
  become: '{{ do_become }}'
  changed_when: "'No uninstalled build requires' not in _nginx_build_dep.stdout|default('')"
  check_mode: no
  failed_when: _nginx_build_dep is failure and 'Exiting on user command' not in _nginx_build_dep.stdout
  register: _nginx_build_dep
  tags: [nginx, packages]  # FIXME Remove when this is fixed https://github.com/ansible/ansible/issues/30882

- name: Install the latest version of required packages
  ansible.builtin.yum:
    name: [openssl, openssl-devel]
    state: present
    update_cache: yes
