---

- name: reload systemd
  command:
    systemctl daemon-reload
  become: '{{ do_become }}'

- name: supervisor restart nginx
  supervisorctl:
    name: nginx
    state: restarted
  become: '{{ do_become }}'

- name: supervisor reload nginx
  command:
    supervisorctl signal HUP nginx
  become: '{{ do_become }}'

- name: system restart nginx
  service:
    name: nginx
    state: restarted
    use: '{{ nginx_daemon_mode }}'
  become: '{{ do_become }}'

- name: system reload nginx
  service:
    name: nginx
    state: reloaded
    use: '{{ nginx_daemon_mode }}'
  become: '{{ do_become }}'
